In [2]:
import pandas as pd

In [3]:

sales=pd.read_excel(r"C:\Users\VISHNU\Downloads\sales_2026.xlsx")
offers=pd.read_excel(r"C:\Users\VISHNU\Downloads\offers.xlsx")
products=pd.read_excel(r"C:\Users\VISHNU\Downloads\products_.xlsx")
stores=pd.read_excel(r"C:\Users\VISHNU\Downloads\stores.xlsx")
customers=pd.read_excel(r"C:\Users\VISHNU\Downloads\customers_.xlsx")

In [20]:
sales.head()

,order_id,order_date,order_time,store_id,customer_id,product_id,offer_id,quantity,payment_mode,order_channel
0,ORD2026000001,2026-01-01 00:00:00,12:11:56,ST001,C03641,P003,OFF01,1,Wallet,Delivery
1,ORD2026000001,2026-01-01 00:00:00,12:11:56,ST001,C03641,P016,OFF01,1,Wallet,Delivery
2,ORD2026000001,2026-01-01 00:00:00,12:11:56,ST001,C03641,P020,OFF01,1,Wallet,Delivery
3,ORD2026000002,2026-01-01 00:00:00,13:12:41,ST025,C05431,P017,OFF01,1,Wallet,Takeaway
4,ORD2026000002,2026-01-01 00:00:00,13:12:41,ST025,C05431,P020,OFF01,2,Wallet,Takeaway

In [23]:
offers.head()

,offer_id,offer_name,discount_pct,start_date,end_date,offer_condition
0,OFF01,No Offer,0.00,NaT,NaT,No discount applied
1,OFF02,Combo Meal Deal,0.10,2026-01-01,2026-12-31,Order has a burger/wrap + fries + beverage
2,OFF03,App Coupon,0.20,2026-01-01,2026-12-31,Orders placed through the app
3,OFF04,Happy Hour,0.15,2026-01-01,2026-12-31,Orders between 3 PM and 6 PM
4,OFF05,BOGO Burger,0.40,2026-01-01,2026-12-31,Buy 1 Get 1 on burgers (blended discount)

In [24]:
products.head()

  product_id            product_name category  unit_price  unit_cost
0       P001     McAloo Tikki Burger  Burgers          69      27.60
1       P002         McVeggie Burger  Burgers         149      62.58
2       P003        McChicken Burger  Burgers         159      71.55
3       P004   McSpicy Paneer Burger  Burgers         199      87.56
4       P005  McSpicy Chicken Burger  Burgers         209      96.14

In [25]:
stores.head()

  store_id                city   state region  store_type  open_date
0    ST001               Kochi  Kerala  South  Drive-Thru 2015-03-29
1    ST002               Kochi  Kerala  South     Dine-In 2020-10-12
2    ST003               Kochi  Kerala  South        Mall 2021-05-13
3    ST004  Thiruvananthapuram  Kerala  South        Mall 2023-03-06
4    ST005  Thiruvananthapuram  Kerala  South        Mall 2021-07-30

In [15]:
customers.head()

  customer_id age_group  gender loyalty_member
0      C00001     25-34  Female              N
1      C00002     18-24    Male              N
2      C00003     25-34  Female              Y
3      C00004     18-24    Male              N
4      C00005     25-34  Female              N

In [6]:
sales.info()
offers.info()
customers.info()
products.info()
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71717 entries, 0 to 71716
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       71717 non-null  object
 1   order_date     71717 non-null  object
 2   order_time     71717 non-null  object
 3   store_id       71717 non-null  object
 4   customer_id    71617 non-null  object
 5   product_id     71717 non-null  object
 6   offer_id       71717 non-null  object
 7   quantity       71717 non-null  int64
 8   payment_mode   71567 non-null  object
 9   order_channel  71717 non-null  object
dtypes: int64(1), object(9)
memory usage: 5.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   offer_id         9 non-null      object
 1   offer_name       9 non-null      object
 2   discount_pct     9 non-null      float64
 3   start_date       8 non-null      datetime64[ns]
 4   end_date         8 non-null      datetime64[ns]
 5   offer_condition  9 non-null      object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 564.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     6000 non-null   object
 1   age_group       6000 non-null   object
 2   gender          6000 non-null   object
 3   loyalty_member  6000 non-null   object
dtypes: object(4)
memory usage: 187.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    30 non-null     object
 1   product_name  30 non-null     object
 2   category      30 non-null     object
 3   unit_price    30 non-null     int64
 4   unit_cost     30 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    43 non-null     object
 1   city        43 non-null     object
 2   state       43 non-null     object
 3   region      43 non-null     object
 4   store_type  43 non-null     object
 5   open_date   43 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 2.1+ KB

In [53]:
print(sales.isnull().sum())
print(customers.isnull().sum())
print(offers.isnull().sum())
print(products.isnull().sum())
print(customers.isnull().sum())

order_id         0
order_date       0
order_time       0
store_id         0
customer_id      0
product_id       0
offer_id         0
quantity         0
payment_mode     0
order_channel    0
dtype: int64
customer_id       0
age_group         0
gender            0
loyalty_member    0
dtype: int64
offer_id           0
offer_name         0
discount_pct       0
start_date         1
end_date           1
offer_condition    0
 start_date        0
dtype: int64
product_id      0
product_name    0
category        0
unit_price      0
unit_cost       0
dtype: int64
customer_id       0
age_group         0
gender            0
loyalty_member    0
dtype: int64

In [34]:
sales["customer_id"] = sales["customer_id"].fillna("Unknown")
sales["payment_mode"] = sales["payment_mode"].fillna("Unknown")

In [44]:

print("Duplicate offers:", offers.duplicated().sum())
print("Duplicate products:", products.duplicated().sum())
print("Duplicate stores:", stores.duplicated().sum())

Duplicate sales: 120
Duplicate offers: 0
Duplicate products: 0
Duplicate customers: 0
Duplicate stores: 0

In [54]:
pip install pandas openpyxl matplotlib seaborn sqlalchemy pymysql

Requirement already satisfied: pandas in c:\users\vishnu\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: openpyxl in c:\users\vishnu\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: matplotlib in c:\users\vishnu\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: seaborn in c:\users\vishnu\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: sqlalchemy in c:\users\vishnu\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\vishnu\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vishnu\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vishnu\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vishnu\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vishnu\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\vishnu\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vishnu\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: greenlet>=1 in c:\users\vishnu\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\vishnu\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\vishnu\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [58]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:mysql40@localhost/mcdonalds"
)
print("connected to MYSQL")

connected to MYSQL

In [59]:
products.to_sql("products", engine, if_exists="replace", index=False)
customers.to_sql("customers", engine, if_exists="replace", index=False)
offers.to_sql("offers", engine, if_exists="replace", index=False)
sales.to_sql("sales", engine, if_exists="replace", index=False)
stores.to_sql("stores", engine, if_exists="replace", index=False)

43